SET time_zone = "+00:00";

CREATE DATABASE IF NOT EXISTS ltdb;

CREATE TABLE ltdb.`users` (
`id` SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`fname` VARCHAR(50) NOT NULL,
`lname` VARCHAR(50) NOT NULL,
`imageType` VARCHAR(255) NOT NULL,
`imageData` LONGBLOB NOT NULL,
`age` INT(5) NOT NULL,
`tel` BIGINT NOT NULL,
`gender` VARCHAR(10) NOT NULL,
`houseno` INT(10) NOT NULL,
`street` VARCHAR(100) NOT NULL,
`city` VARCHAR(100) NOT NULL,
`postcode` VARCHAR(50) NOT NULL,
`username` VARCHAR(50) NOT NULL,
`email` VARCHAR(50) NOT NULL,
`password` VARCHAR(100) NOT NULL,
`bio` LONGTEXT NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE ltdb.`admin` (
`id` SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`name` VARCHAR(50) NOT NULL,
`password` VARCHAR(50) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE ltdb.`packages` (
`id` SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`imageType` VARCHAR(255) NOT NULL,
`imageData` LONGBLOB NOT NULL,
`name` VARCHAR(100) NOT NULL,
`location` VARCHAR(100) NOT NULL,
`price` DOUBLE NOT NULL,
`details` TEXT NOT NULL,
`creationDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updationDate` TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE ltdb.`booking` (
`bookingsId` SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`packageId` INT(10) NOT NULL,
`bookDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`submittedBy` VARCHAR(50) NOT NULL,
`travelDate` VARCHAR(100) NOT NULL,
`status` VARCHAR(10) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE ltdb.`complain` (
`id` SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`update_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`submitted_by` VARCHAR(50) NOT NULL,
`sent_to` VARCHAR(50) NOT NULL,
`message` VARCHAR(8000) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `admin` (`name`, `password`) VALUES ('admin: Pete', MD5('admin'));
INSERT INTO `admin` (`name`, `password`) VALUES ('admin: Cosmin', MD5('admin123'));